### ISSUE TITLE
This and BirdNET-Pi

### ISSUE THREAD

**Issue by mcguirepr89** [aiXander/Realtime_PyAudio_FFT#24]
Howdy!!! I just wanted to say thank for this repo and the time you spent putting it together. I'll be looking at bringing this into [BirdNET-Pi](https://github.com/mcguirepr89/BirdNET-Pi.git) for realtime spectrograms and the development I'm doing around bats :)

My very best regards,
Patrick

**Comment by aiXander** [comment]
You're very welcome, glad you find it valuable :)
